name: deploy to azure container instances

on:
  workflow_dispatch:
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "kraken-devs/safe-settings"
  TAG: "2.0.0"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ vars.AZURE_RG }}
          dns-name-label: url-for-container
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          name: ${{ vars.AZURE_CI_NAME }} 
          location: ${{ vars.AZURE_LOCATION }}
          secure-environment-variables: APP_ID=${{ sectrets.APP_ID }} PRIVATE_KEY=${{ sectrets.PRIVATE_KEY }} WEBHOOK_SECRET=${{ sectrets.WEBHOOK_SECRET }}

            
  
            