name: deploy to azure container instances

on:
  workflow_dispatch:
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "kraken-devs/safe-settings"
  TAG: "2.0.0"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}
      
      - name: ghcr login
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker pull
        run: docker pull ghcr.io/kraken-devs/safe-settings@sha256:9e4492eae83b45aaa7980c9bc52917f9e609e69690505ac8ca0717bfa0410621

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1.1.3'
        with:
          resource-group: ${{ vars.AZURE_RG }}
          dns-name-label: urlforcontainer
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          name: contoso-container
          location: 'east us'
          registry-login-server: ghcr.io
          registry-username: sebastianramospina
          registry-password: ${{ secrets.REGISTRY_TOKEN }}
  
            