name: deploy to azure container instances

on:
  workflow_dispatch:
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "kraken-devs/safe-settings"
  TAG: "2.0.0"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1.1.3'
        with:
          resource-group: ${{ vars.AZURE_RG }}
          dns-name-label: url-for-container
          image: nginx
          name: contoso-container
          location: 'east us'
            
  
            