name: deploy to azure container instances

on:
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
       


      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1.1.3'
        with:
          resource-group: ${{ vars.AZURE_RG }}
          dns-name-label: krakendevssafesettings
          image: ghcr.io/kraken-devs/safe-settings:main-enterprise
          name: draken-devs-safesettings
          location: 'east us'
          ports: 3000
          registry-login-server: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.REGISTRY_TOKEN }}
          secure-environment-variables: GH_ORG=${{ secrets.DEPLOY_GH_ORG }} APP_ID=${{ secrets.APP_ID }} PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
